name: Build Minimal FFmpeg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout FFmpeg
        uses: actions/checkout@v4
        with:
          ref: n8.1.2
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            yasm \
            nasm

      - name: Configure
        run: |
            ./configure \
            --prefix="$GITHUB_WORKSPACE/build" \
            --disable-everything \
            --enable-ffmpeg \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-doc \
            --disable-debug \
            --disable-network \
            --disable-shared \
            --enable-static \
            \
            --enable-protocol=file \
            --enable-muxer=mp4

      - name: Build
        run: |
          make -j$(nproc)
          make install

      - name: Upload ffmpeg
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-n8.1.2-linux
          path: |
            build/bin/ffmpeg
